package events

import "reflect"

type Event interface {
	Ready |
		Resumed |
		Reconnect |
		InvalidSession |
		ChannelCreate |
		ChannelUpdate |
		ChannelDelete |
		ChannelPinsUpdate |
		GuildCreate |
		GuildUpdate |
		GuildDelete |
		GuildBanAdd |
		GuildBanRemove |
		GuildEmojisUpdate |
		GuildIntegrationsUpdate |
		GuildMemberAdd |
		GuildMemberRemove |
		GuildMemberUpdate |
		GuildMembersChunk |
		GuildRoleCreate |
		GuildRoleUpdate |
		GuildRoleDelete |
		InviteCreate |
		InviteDelete |
		MessageCreate |
		MessageUpdate |
		MessageDelete |
		MessageDeleteBulk |
		MessageReactionAdd |
		MessageReactionRemove |
		MessageReactionRemoveAll |
		MessageReactionRemoveEmoji |
		PresenceUpdate |
		ThreadCreate |
		ThreadUpdate |
		ThreadDelete |
		ThreadListSync |
		ThreadMembersUpdate |
		ThreadMemberUpdate |
		TypingStart |
		UserUpdate |
		VoiceServerUpdate |
		VoiceStateUpdate |
		WebhooksUpdate
}

var EventTypes = map[EventType]reflect.Type{
	READY:                         reflect.TypeOf(Ready{}),
	RESUMED:                       reflect.TypeOf(Resumed{}),
	RECONNECT:                     reflect.TypeOf(Reconnect{}),
	INVALID_SESSION:               reflect.TypeOf(InvalidSession{}),
	CHANNEL_CREATE:                reflect.TypeOf(ChannelCreate{}),
	CHANNEL_UPDATE:                reflect.TypeOf(ChannelUpdate{}),
	CHANNEL_DELETE:                reflect.TypeOf(ChannelDelete{}),
	CHANNEL_PINS_UPDATE:           reflect.TypeOf(ChannelPinsUpdate{}),
	GUILD_CREATE:                  reflect.TypeOf(GuildCreate{}),
	GUILD_UPDATE:                  reflect.TypeOf(GuildUpdate{}),
	GUILD_DELETE:                  reflect.TypeOf(GuildDelete{}),
	GUILD_BAN_ADD:                 reflect.TypeOf(GuildBanAdd{}),
	GUILD_BAN_REMOVE:              reflect.TypeOf(GuildBanRemove{}),
	GUILD_EMOJIS_UPDATE:           reflect.TypeOf(GuildEmojisUpdate{}),
	GUILD_INTEGRATIONS_UPDATE:     reflect.TypeOf(GuildIntegrationsUpdate{}),
	GUILD_MEMBER_ADD:              reflect.TypeOf(GuildMemberAdd{}),
	GUILD_MEMBER_REMOVE:           reflect.TypeOf(GuildMemberRemove{}),
	GUILD_MEMBER_UPDATE:           reflect.TypeOf(GuildMemberUpdate{}),
	GUILD_MEMBERS_CHUNK:           reflect.TypeOf(GuildMembersChunk{}),
	GUILD_ROLE_CREATE:             reflect.TypeOf(GuildRoleCreate{}),
	GUILD_ROLE_UPDATE:             reflect.TypeOf(GuildRoleUpdate{}),
	GUILD_ROLE_DELETE:             reflect.TypeOf(GuildRoleDelete{}),
	INVITE_CREATE:                 reflect.TypeOf(InviteCreate{}),
	INVITE_DELETE:                 reflect.TypeOf(InviteDelete{}),
	MESSAGE_CREATE:                reflect.TypeOf(MessageCreate{}),
	MESSAGE_UPDATE:                reflect.TypeOf(MessageUpdate{}),
	MESSAGE_DELETE:                reflect.TypeOf(MessageDelete{}),
	MESSAGE_DELETE_BULK:           reflect.TypeOf(MessageDeleteBulk{}),
	MESSAGE_REACTION_ADD:          reflect.TypeOf(MessageReactionAdd{}),
	MESSAGE_REACTION_REMOVE:       reflect.TypeOf(MessageReactionRemove{}),
	MESSAGE_REACTION_REMOVE_ALL:   reflect.TypeOf(MessageReactionRemoveAll{}),
	MESSAGE_REACTION_REMOVE_EMOJI: reflect.TypeOf(MessageReactionRemoveEmoji{}),
	PRESENCE_UPDATE:               reflect.TypeOf(PresenceUpdate{}),
	THREAD_CREATE:                 reflect.TypeOf(ThreadCreate{}),
	THREAD_UPDATE:                 reflect.TypeOf(ThreadUpdate{}),
	THREAD_DELETE:                 reflect.TypeOf(ThreadDelete{}),
	THREAD_LIST_SYNC:              reflect.TypeOf(ThreadListSync{}),
	THREAD_MEMBER_UPDATE:          reflect.TypeOf(ThreadMemberUpdate{}),
	THREAD_MEMBERS_UPDATE:         reflect.TypeOf(ThreadMembersUpdate{}),
	TYPING_START:                  reflect.TypeOf(TypingStart{}),
	USER_UPDATE:                   reflect.TypeOf(UserUpdate{}),
	VOICE_STATE_UPDATE:            reflect.TypeOf(VoiceStateUpdate{}),
	VOICE_SERVER_UPDATE:           reflect.TypeOf(VoiceStateUpdate{}),
	WEBHOOKS_UPDATE:               reflect.TypeOf(WebhooksUpdate{}),
}
