package events

type EventType string

const (
	READY                         EventType = "READY"
	RESUMED                       EventType = "RESUMED"
	RECONNECT                     EventType = "RECONNECT"
	INVALID_SESSION               EventType = "INVALID_SESSION"
	CHANNEL_CREATE                EventType = "CHANNEL_CREATE"
	CHANNEL_UPDATE                EventType = "CHANNEL_UPDATE"
	CHANNEL_DELETE                EventType = "CHANNEL_DELETE"
	CHANNEL_PINS_UPDATE           EventType = "CHANNEL_PINS_UPDATE"
	ENTITLEMENT_CREATE            EventType = "ENTITLEMENT_CREATE"
	ENTITLEMENT_UPDATE            EventType = "ENTITLEMENT_UPDATE"
	ENTITLEMENT_DELETE            EventType = "ENTITLEMENT_DELETE"
	GUILD_CREATE                  EventType = "GUILD_CREATE"
	GUILD_UPDATE                  EventType = "GUILD_UPDATE"
	GUILD_DELETE                  EventType = "GUILD_DELETE"
	GUILD_BAN_ADD                 EventType = "GUILD_BAN_ADD"
	GUILD_BAN_REMOVE              EventType = "GUILD_BAN_REMOVE"
	GUILD_EMOJIS_UPDATE           EventType = "GUILD_EMOJIS_UPDATE"
	GUILD_INTEGRATIONS_UPDATE     EventType = "GUILD_INTEGRATIONS_UPDATE"
	GUILD_MEMBER_ADD              EventType = "GUILD_MEMBER_ADD"
	GUILD_MEMBER_REMOVE           EventType = "GUILD_MEMBER_REMOVE"
	GUILD_MEMBER_UPDATE           EventType = "GUILD_MEMBER_UPDATE"
	GUILD_MEMBERS_CHUNK           EventType = "GUILD_MEMBERS_CHUNK"
	GUILD_ROLE_CREATE             EventType = "GUILD_ROLE_CREATE"
	GUILD_ROLE_UPDATE             EventType = "GUILD_ROLE_UPDATE"
	GUILD_ROLE_DELETE             EventType = "GUILD_ROLE_DELETE"
	INVITE_CREATE                 EventType = "INVITE_CREATE"
	INVITE_DELETE                 EventType = "INVITE_DELETE"
	MESSAGE_CREATE                EventType = "MESSAGE_CREATE"
	MESSAGE_UPDATE                EventType = "MESSAGE_UPDATE"
	MESSAGE_DELETE                EventType = "MESSAGE_DELETE"
	MESSAGE_DELETE_BULK           EventType = "MESSAGE_DELETE_BULK"
	MESSAGE_REACTION_ADD          EventType = "MESSAGE_REACTION_ADD"
	MESSAGE_REACTION_REMOVE       EventType = "MESSAGE_REACTION_REMOVE"
	MESSAGE_REACTION_REMOVE_ALL   EventType = "MESSAGE_REACTION_REMOVE_ALL"
	MESSAGE_REACTION_REMOVE_EMOJI EventType = "MESSAGE_REACTION_REMOVE_EMOJI"
	PRESENCE_UPDATE               EventType = "PRESENCE_UPDATE"
	THREAD_CREATE                 EventType = "THREAD_CREATE"
	THREAD_UPDATE                 EventType = "THREAD_UPDATE"
	THREAD_DELETE                 EventType = "THREAD_DELETE"
	THREAD_LIST_SYNC              EventType = "THREAD_LIST_SYNC"
	THREAD_MEMBER_UPDATE          EventType = "THREAD_MEMBER_UPDATE"
	THREAD_MEMBERS_UPDATE         EventType = "THREAD_MEMBERS_UPDATE"
	TYPING_START                  EventType = "TYPING_START"
	USER_UPDATE                   EventType = "USER_UPDATE"
	VOICE_STATE_UPDATE            EventType = "VOICE_STATE_UPDATE"
	VOICE_SERVER_UPDATE           EventType = "VOICE_SERVER_UPDATE"
	WEBHOOKS_UPDATE               EventType = "WEBHOOKS_UPDATE"
)
